pipeline:
  checkout:
    image: docker.moxa.online/build/amd64-debian:jessie
    commands:
      - git checkout --track -b ${DRONE_BRANCH} origin/${DRONE_BRANCH}
      - git merge ${CI_COMMIT_BRANCH}
    when:
      event:
        exclude: [ pull_request, tag ]
      branch:
        exclude: [ master ]
      local: false

  test:
    image: docker.moxa.online/build/amd64-debian-python:jessie
    commands:
      - set-cache; set
      - pip install -r requirements.txt
      - make test
    volumes:
      - /var/tmp:/var/tmp:z

  build_pkgs:
    image: docker.moxa.online/build/amd64-debian-python:jessie
    commands:
      - set-cache; set
      - make dist
      - make -C build-deb
    volumes:
      - /var/tmp:/var/tmp:z

  upload_experimental_deb_pkgs:
    image: docker.moxa.online/build/amd64-debian:jessie
    environment:
      - DEB_TARGET=/mnt/storage/repo/debian/jessie/thingspro/pool/experimental/main/cg-bundle
      - DEB_ASSETS=./build-deb/*.deb ./build-deb/*.dsc ./build-deb/*.changes
    commands:
      - mkdir -p $${DEB_TARGET}
      - cp $${DEB_ASSETS} $${DEB_TARGET}
      - find $${DEB_TARGET} -name '*.deb' -printf "%T+  %p \n" | sort -nr | head -n 1 | sed 's/\\/mnt\\/storage\\/repo/http:\\/\\/repo.isd.moxa.com/g'
    when:
      branch: develop
      event: [ push, pull_request ]
    volumes:
      - /mnt/storage:/mnt/storage:z

  upload_unstable_deb_pkgs:
    image: docker.moxa.online/build/amd64-debian:jessie
    environment:
      - DEB_TARGET=/mnt/storage/repo/debian/jessie/thingspro/pool/unstable/main/cg-bundle
      - DEB_ASSETS=./build-deb/*.deb ./build-deb/*.dsc ./build-deb/*.changes
    commands:
      - mkdir -p $${DEB_TARGET}
      - cp $${DEB_ASSETS} $${DEB_TARGET}
      - find $${DEB_TARGET} -name '*.deb' -printf "%T+  %p \n" | sort -nr | head -n 1 | sed 's/\\/mnt\\/storage\\/repo/http:\\/\\/repo.isd.moxa.com/g'
    when:
      branch: develop
      event: [ push, deployment ]
    volumes:
      - /mnt/storage:/mnt/storage:z

  upload_release_deb_pkgs:
    image: docker.moxa.online/build/amd64-debian:jessie
    environment:
      - DEB_TARGET=/mnt/storage/repo/debian/jessie/thingspro/pool/$${CI_COMMIT_BRANCH}/main/cg-bundle
      - DEB_ASSETS=./build-deb/*.deb ./build-deb/*.dsc ./build-deb/*.changes
    commands:
      - mkdir -p $${DEB_TARGET}
      - cp $${DEB_ASSETS} $${DEB_TARGET}
      - find $${DEB_TARGET} -name '*.deb' -printf "%T+  %p \n" | sort -nr | head -n 1 | sed 's/\\/mnt\\/storage\\/repo/http:\\/\\/repo.isd.moxa.com/g'
    when:
      branch: release/*
      event: [ push, deployment ]
    volumes:
      - /mnt/storage:/mnt/storage:z

  upload_stable_deb_pkgs:
    image: docker.moxa.online/build/amd64-debian:jessie
    environment:
      - DEB_TARGET=/mnt/storage/repo/debian/jessie/thingspro/pool/stable/main/cg-bundle
      - DEB_ASSETS=./build-deb/*.deb ./build-deb/*.dsc ./build-deb/*.changes
    commands:
      - mkdir -p $${DEB_TARGET}
      - cp $${DEB_ASSETS} $${DEB_TARGET}
      - find $${DEB_TARGET} -name '*.deb' -printf "%T+  %p \n" | sort -nr | head -n 1 | sed 's/\\/mnt\\/storage\\/repo/http:\\/\\/repo.isd.moxa.com/g'
    when:
      branch: master
      event: [ push, deployment ]
    volumes:
      - /mnt/storage:/mnt/storage:z

  upload_tag_deb_pkgs:
    image: docker.moxa.online/build/amd64-debian:jessie
    environment:
      - DEB_TARGET=/mnt/storage/repo/debian/jessie/thingspro/pool/tag/${CI_TAG}/cg-bundle
      - DEB_ASSETS=./build-deb/*.deb ./build-deb/*.dsc ./build-deb/*.changes
    commands:
      - mkdir -p $${DEB_TARGET}
      - cp $${DEB_ASSETS} $${DEB_TARGET}
      - find $${DEB_TARGET} -name '*.deb' -printf "%T+  %p \n" | sort -nr | head -n 1 | sed 's/\\/mnt\\/storage\\/repo/http:\\/\\/repo.isd.moxa.com/g'
    when:
      event: [ tag ]
    volumes:
      - /mnt/storage:/mnt/storage:z

  dpkg_scanpackages:
    image: docker.moxa.online/plugins/debian-repo-update:latest
    environment:
      - OS_VER=jessie
      - REPO=thingspro
      - BRANCH=${DRONE_BRANCH}
    when:
      branch: [ develop, release/*, master ]
      event: [ push, pull_request ]
      status: success
    volumes:
      - /mnt/storage:/mnt/storage:z

  notify_to_slack_channel:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: droneci
    username: drone
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
        - *repo:* {{repo.name}}
        - *author:* {{build.author}}
        - *event:* {{build.event}}
        - *commit:* {{build.commit}}
        - *link:* {{build.link}}
      {{else}}
        build {{build.number}} failed. Fix me please.
        - *repo:* {{repo.name}}
        - *author:* {{build.author}}
        - *event:* {{build.event}}
        - *commit:* {{build.commit}}
        - *link:* {{build.link}}
      {{/success}}
